"""The desktop object each app supplies. The agent only calls these methods."""

from __future__ import annotations

import threading
from typing import Protocol

from openctrl.screen import Shot


class Desktop(Protocol):
    shell_name: str

    def push_awake(self) -> None: ...

    def pop_awake(self) -> None: ...

    def screen_locked(self) -> str | None: ...

    def run_shell(self, command: str, cancel: threading.Event, timeout: float, cwd: str | None) -> str: ...

    def list_windows(self) -> str: ...

    def foreground(self) -> str: ...

    def focus_window(self, title: str) -> str: ...

    def ui_tree(self, title: str | None, max_depth: int, max_nodes: int) -> str: ...

    def click_control(self, name: str, window: str | None, control_type: str | None) -> str: ...

    def type_text(self, text: str, window: str | None, control_name: str | None, clear: bool) -> str: ...

    def press_keys(self, keys: str) -> str: ...

    def launch(self, target: str, args: str) -> str: ...

    def screenshot(self, window: str | None) -> Shot: ...

    def click(self, x: int, y: int, button: str, coordinate_space: str) -> str: ...

    def scroll(self, direction: str, amount: int, x: int | None, y: int | None, coordinate_space: str) -> str: ...

    def drag(self, x1: int, y1: int, x2: int, y2: int, coordinate_space: str) -> str: ...

    def clipboard_get(self) -> str: ...

    def clipboard_set(self, text: str) -> str: ...

    def cursor_prompt(self, folder: str, text: str, send: bool) -> str: ...

    def window_action(self, title: str, action: str, monitor: int) -> str: ...
